"""
HTML Report Generator
Generates downloadable HTML report for band analysis results.
"""

from typing import Dict, List, Optional
from datetime import datetime
from pathlib import Path

from ..core.band_tracer import BandTraceResult, BandStatus, FinalStatus
from ..core.analyzer import AnalysisResult


class HTMLReport:
    """Generates HTML report"""

    def __init__(self, result: AnalysisResult, claude_review: Optional[str] = None):
        self.result = result
        self.tracer = result.tracer
        self.trace_results = result.trace_results
        self.summary = result.summary
        self.anomalies = result.anomalies
        self.claude_review = claude_review

    def generate(self, output_path: Optional[str] = None) -> str:
        """Generate HTML report"""
        html = self._build_html()

        if output_path:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html)
            print(f"[INFO] HTML report written to: {output_path}")

        return html

    def _build_html(self) -> str:
        """Build complete HTML document"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Band Analysis Report</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Band Analysis Report</h1>
            <p class="timestamp">Generated: {timestamp}</p>
        </header>

        {self._document_status_html()}
        {self._summary_html()}
        {self._band_table_html("LTE (4G)", self.trace_results.get('LTE', []), 'B', 'lte')}
        {self._band_table_html("NR SA (5G Standalone)", self.trace_results.get('NR_SA', []), 'n', 'nr-sa')}
        {self._band_table_html("NR NSA (5G Non-Standalone)", self.trace_results.get('NR_NSA', []), 'n', 'nr-nsa')}
        {self._anomalies_html()}
        {self._claude_review_html()}

        <footer>
            <p>Generated by Band Combos Analyzer Tool</p>
        </footer>
    </div>
    <script>
        {self._get_javascript()}
    </script>
</body>
</html>"""

    def _get_css(self) -> str:
        """Get CSS styles"""
        return """
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            line-height: 1.6;
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background: linear-gradient(135deg, #1e3c72, #2a5298);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
        }

        header h1 {
            margin-bottom: 10px;
        }

        .timestamp {
            opacity: 0.8;
            font-size: 0.9em;
        }

        .section {
            background: white;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            overflow: hidden;
        }

        .section-header {
            background: linear-gradient(135deg, #1e3c72, #2a5298);
            color: white;
            padding: 15px 20px;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            align-items: center;
            user-select: none;
        }

        .section-header:hover {
            background: linear-gradient(135deg, #2a5298, #1e3c72);
        }

        .section-header h2 {
            margin: 0;
            font-size: 1.2em;
        }

        .section-header .toggle-icon {
            font-size: 1.5em;
            transition: transform 0.3s ease;
        }

        .section-header.collapsed .toggle-icon {
            transform: rotate(-90deg);
        }

        .section-content {
            padding: 20px;
            transition: max-height 0.3s ease-out;
            overflow: hidden;
        }

        .section-content.collapsed {
            max-height: 0;
            padding: 0 20px;
        }

        .doc-status {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 10px;
        }

        .doc-item {
            padding: 10px;
            border-radius: 5px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .doc-item.loaded {
            background-color: #e8f5e9;
            border-left: 4px solid #4caf50;
        }

        .doc-item.missing {
            background-color: #fff3e0;
            border-left: 4px solid #ff9800;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
        }

        .summary-card {
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            padding: 20px;
            border-radius: 10px;
            text-align: center;
        }

        .summary-card.lte {
            background: linear-gradient(135deg, #11998e, #38ef7d);
        }

        .summary-card.nr-sa {
            background: linear-gradient(135deg, #667eea, #764ba2);
        }

        .summary-card.nr-nsa {
            background: linear-gradient(135deg, #f093fb, #f5576c);
        }

        .summary-card h3 {
            font-size: 0.9em;
            opacity: 0.9;
            margin-bottom: 5px;
        }

        .summary-card .number {
            font-size: 2em;
            font-weight: bold;
        }

        .summary-card .details {
            font-size: 0.8em;
            opacity: 0.8;
            margin-top: 5px;
        }

        .table-container {
            overflow-x: auto;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.85em;
            min-width: 900px;
        }

        th, td {
            padding: 8px 6px;
            text-align: center;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #1e3c72;
            color: white;
            font-weight: 500;
            position: sticky;
            top: 0;
        }

        tr:hover {
            background-color: #f5f5f5;
        }

        .status-pass {
            color: #4caf50;
            font-weight: bold;
        }

        .status-fail {
            color: #f44336;
            font-weight: bold;
        }

        .status-na {
            color: #9e9e9e;
        }

        .status-skip {
            color: #9e9e9e;
            font-style: italic;
        }

        .final-enabled {
            background-color: #e8f5e9;
            color: #2e7d32;
            font-weight: bold;
        }

        .final-filtered {
            background-color: #fff3e0;
            color: #ef6c00;
        }

        .final-anomaly {
            background-color: #ffebee;
            color: #c62828;
            font-weight: bold;
        }

        .anomaly-list {
            list-style: none;
        }

        .anomaly-item {
            background-color: #ffebee;
            border-left: 4px solid #f44336;
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 0 5px 5px 0;
        }

        .anomaly-item h4 {
            color: #c62828;
            margin-bottom: 5px;
        }

        .claude-review {
            background-color: #e3f2fd;
            border-left: 4px solid #2196f3;
            padding: 20px;
            white-space: pre-wrap;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 0.85em;
            overflow-x: auto;
        }

        footer {
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 0.9em;
        }

        .badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 0.75em;
            font-weight: bold;
            margin-left: 10px;
        }

        .badge-count {
            background-color: rgba(255,255,255,0.3);
        }

        .badge-anomaly {
            background-color: #f44336;
        }

        @media (max-width: 768px) {
            .summary-grid {
                grid-template-columns: 1fr;
            }

            table {
                font-size: 0.75em;
            }

            th, td {
                padding: 4px 3px;
            }
        }
        """

    def _get_javascript(self) -> str:
        """Get JavaScript for interactivity"""
        return """
        document.addEventListener('DOMContentLoaded', function() {
            // Add click handlers to all section headers
            document.querySelectorAll('.section-header').forEach(function(header) {
                header.addEventListener('click', function() {
                    const content = this.nextElementSibling;
                    this.classList.toggle('collapsed');
                    content.classList.toggle('collapsed');
                });
            });
        });
        """

    def _document_status_html(self) -> str:
        """Generate document status section"""
        items = []
        for stage, status in self.tracer.doc_status.items():
            css_class = "loaded" if status.loaded else "missing"
            icon = "&#10004;" if status.loaded else "&#10008;"
            details = status.details if status.loaded else "Not provided"
            items.append(f"""
                <div class="doc-item {css_class}">
                    <span>{icon}</span>
                    <div>
                        <strong>{status.name}</strong>
                        <br><small>{details}</small>
                    </div>
                </div>
            """)

        return f"""
        <div class="section">
            <div class="section-header">
                <h2>Document Status</h2>
                <span class="toggle-icon">&#9660;</span>
            </div>
            <div class="section-content">
                <div class="doc-status">
                    {''.join(items)}
                </div>
            </div>
        </div>
        """

    def _summary_html(self) -> str:
        """Generate summary section"""
        s = self.summary
        return f"""
        <div class="section">
            <div class="section-header">
                <h2>Summary</h2>
                <span class="toggle-icon">&#9660;</span>
            </div>
            <div class="section-content">
                <div class="summary-grid">
                    <div class="summary-card lte">
                        <h3>LTE (4G)</h3>
                        <div class="number">{s.lte_enabled}/{s.lte_total}</div>
                        <div class="details">{s.lte_filtered} filtered, {s.lte_anomalies} anomalies</div>
                    </div>
                    <div class="summary-card nr-sa">
                        <h3>NR SA (5G)</h3>
                        <div class="number">{s.nr_sa_enabled}/{s.nr_sa_total}</div>
                        <div class="details">{s.nr_sa_filtered} filtered, {s.nr_sa_anomalies} anomalies</div>
                    </div>
                    <div class="summary-card nr-nsa">
                        <h3>NR NSA (5G)</h3>
                        <div class="number">{s.nr_nsa_enabled}/{s.nr_nsa_total}</div>
                        <div class="details">{s.nr_nsa_filtered} filtered, {s.nr_nsa_anomalies} anomalies</div>
                    </div>
                </div>
            </div>
        </div>
        """

    def _band_table_html(self, title: str, results: List[BandTraceResult], prefix: str, css_id: str) -> str:
        """Generate band tracing table with NV_Pref column"""
        if not results:
            return ""

        # Count stats for badge
        enabled_count = sum(1 for r in results if r.final_status == FinalStatus.ENABLED)
        anomaly_count = sum(1 for r in results if r.final_status in [FinalStatus.ANOMALY, FinalStatus.MISSING_IN_PM, FinalStatus.MISSING_IN_UE])

        rows = []
        for r in results:
            band_name = f"{prefix}{r.band_num}"

            def cell(s: BandStatus) -> str:
                if s == BandStatus.PASS:
                    return '<td class="status-pass">OK</td>'
                elif s == BandStatus.FAIL:
                    return '<td class="status-fail">X</td>'
                elif s == BandStatus.NA:
                    return '<td class="status-na">-</td>'
                return '<td class="status-skip">.</td>'

            # Final status styling
            if r.final_status == FinalStatus.ENABLED:
                final_class = "final-enabled"
            elif r.final_status in [FinalStatus.ANOMALY, FinalStatus.MISSING_IN_PM, FinalStatus.MISSING_IN_UE]:
                final_class = "final-anomaly"
            else:
                final_class = "final-filtered"

            row = f"""
            <tr>
                <td><strong>{band_name}</strong></td>
                {cell(r.stages.get('RFC', BandStatus.NA))}
                {cell(r.stages.get('HW_Filter', BandStatus.NA))}
                {cell(r.stages.get('Carrier', BandStatus.NA))}
                {cell(r.stages.get('Generic', BandStatus.NA))}
                {cell(r.stages.get('NV_Pref', BandStatus.NA))}
                {cell(r.stages.get('QXDM', BandStatus.NA))}
                {cell(r.stages.get('UE_Cap', BandStatus.NA))}
                <td class="{final_class}">{r.final_status.value}</td>
                <td>{r.filtered_at or '-'}</td>
            </tr>
            """
            rows.append(row)

        badge_html = f'<span class="badge badge-count">{enabled_count}/{len(results)}</span>'
        if anomaly_count > 0:
            badge_html += f'<span class="badge badge-anomaly">{anomaly_count} anomalies</span>'

        return f"""
        <div class="section" id="{css_id}">
            <div class="section-header">
                <h2>{title} {badge_html}</h2>
                <span class="toggle-icon">&#9660;</span>
            </div>
            <div class="section-content">
                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Band</th>
                                <th>RFC</th>
                                <th>HW</th>
                                <th>Carrier</th>
                                <th>Generic</th>
                                <th>NV Pref</th>
                                <th>QXDM</th>
                                <th>UE Cap</th>
                                <th>Status</th>
                                <th>Filtered At</th>
                            </tr>
                        </thead>
                        <tbody>
                            {''.join(rows)}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        """

    def _anomalies_html(self) -> str:
        """Generate anomalies section"""
        if not self.anomalies:
            return """
            <div class="section">
                <div class="section-header">
                    <h2>Anomalies <span class="badge badge-count">0</span></h2>
                    <span class="toggle-icon">&#9660;</span>
                </div>
                <div class="section-content">
                    <p style="color: #4caf50; padding: 10px;">&#10004; No anomalies detected.</p>
                </div>
            </div>
            """

        items = []
        for anomaly in self.anomalies:
            items.append(f"""
            <div class="anomaly-item">
                <h4>{anomaly['band']} ({anomaly['type']})</h4>
                <p>{anomaly['reason']}</p>
            </div>
            """)

        return f"""
        <div class="section">
            <div class="section-header">
                <h2>Anomalies <span class="badge badge-anomaly">{len(self.anomalies)}</span></h2>
                <span class="toggle-icon">&#9660;</span>
            </div>
            <div class="section-content">
                <div class="anomaly-list">
                    {''.join(items)}
                </div>
            </div>
        </div>
        """

    def _claude_review_html(self) -> str:
        """Generate Claude review section if available"""
        if not self.claude_review:
            return ""

        return f"""
        <div class="section">
            <div class="section-header">
                <h2>AI Expert Review</h2>
                <span class="toggle-icon">&#9660;</span>
            </div>
            <div class="section-content">
                <div class="claude-review">
{self.claude_review}
                </div>
            </div>
        </div>
        """


def generate_html_report(result: AnalysisResult, output_path: Optional[str] = None,
                         claude_review: Optional[str] = None) -> str:
    """Convenience function to generate HTML report"""
    report = HTMLReport(result, claude_review)
    return report.generate(output_path)
